---
title: "Dataprep Partner Paper"
author: "Thijmen Jeroense"
bibliography: references.bib
date: "Last compiled on `r format(Sys.time(), '%B, %Y')`"
output: 
  html_document:
    toc:  true
    toc_float: true
    number_sections: false
    code_folding: show
    code_download: yes
---

```{r setup,globalsettings, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE, cache=TRUE, results="hold", eval=FALSE, class.source=c("test"))
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"), results="hold", eval=FALSE)
options(width = 100)

colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color, 
      x)
  } else x
}

```


```{r klippy, echo=FALSE, include=TRUE, eval=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```



```{css, echo=FALSE, eval=TRUE}
pre {
  max-height: 300px;
  overflow-y: auto;
}

.watch-out {
  background-color: lightpink;
  border: 3px solid red;
  font-weight: bold;
}


pre.test {
  max-height: 300px;
  overflow-y: auto;
  overflow-x: auto;
  margin: 0px;
}

pre.test2 {
  max-height: 300px;
  overflow-y: auto;
  overflow-x: auto;
  margin: 0px;
  background-color: white
}


h1, .h1, h2, .h2, h3, .h3 {
    margin-top: 24px;
}


```

```{r packages, class.source="watch-out"}
#load packages.
library(dplyr)
library(haven)
library(purrr)
```